#!/bin/bash

# Check if SQL file is provided
if [[ $# -ne 1 ]]; then
	echo "Usage: $0 <sql_file>"
	exit 1
fi

# Recreate database
mysql -h $DB_HOST -u $DB_USER -p$DB_PASSWORD -e "DROP DATABASE $DB_DATABASE;"
mysql -h $DB_HOST -u $DB_USER -p$DB_PASSWORD -e "CREATE DATABASE $DB_DATABASE;"
