#!/bin/bash

# Check if dump file is provided
if [[ $# -ne 1 ]]; then
    echo "Usage: $0 <dump_file>"
    exit 1
fi

DUMP_FILE=$1

# Check if the SQL file exists
if [[ -f $DUMP_FILE ]]; then
    echo "Dump file already exists: $DUMP_FILE"
    exit 1
fi

# Recreate database
mysql -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASSWORD" -e "CREATE DATABASE IF NOT EXISTS $DB_DATABASE"

# Export database to SQL file
mysqldump -h $DB_HOST -u $DB_USER -p$DB_PASSWORD $DB_DATABASE > "$DUMP_FILE"
