#!/bin/bash

# Check if SQL file is provided
if [[ $# -ne 1 ]]; then
    echo "Usage: $0 <sql_file>"
    exit 1
fi

SQL_FILE=$1

# Check if the SQL file exists
if [[ ! -f $SQL_FILE ]]; then
    echo "SQL file not found: $SQL_FILE"
    exit 1
fi

# Recreate database
mysql -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASSWORD" -e "DROP DATABASE IF EXISTS $DB_DATABASE;"
mysql -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASSWORD" -e "CREATE DATABASE $DB_DATABASE;"

# Import SQL file into database
mysql -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASSWORD" "$DB_DATABASE" < "$SQL_FILE"