FROM pixnyb/%image% as base

USER root

RUN add-apt-repository ppa:ondrej/php -y && \
    apt-get update && apt-get install -y \
    apache2 \
    libapache2-mod-php7.4 \
    php7.4-cli \
    php7.4-bcmath \
    php7.4-curl \
    php7.4-mbstring \
    php7.4-mysql \
    php7.4-tokenizer \
    php7.4-xml \
    php7.4-zip \
    php7.4-gd \
    php7.4-intl \
    && sudo rm -rf /var/lib/apt/lists/*

RUN curl -sS https://getcomposer.org/installer | php \
    && mv composer.phar /usr/local/bin/composer

RUN echo 'export PATH="$PATH:$HOME/.composer/vendor/bin"' >> /root/.bashrc

RUN a2enmod rewrite

RUN chmod 777 /var/www/html

ENV EXTENSION_LIST="christian-kohler.path-intellisense,formulahendry.auto-close-tag,formulahendry.auto-rename-tag"

USER vscode

EXPOSE 80