FROM pixnyb/%image% as base

USER root

RUN add-apt-repository ppa:ondrej/php -y && \
    apt-get update && apt-get install -y \
    apache2 \
    libapache2-mod-php8.0 \
    php8.0-cli \
    php8.0-bcmath \
    php8.0-curl \
    php8.0-mbstring \
    php8.0-mysql \
    php8.0-tokenizer \
    php8.0-xml \
    php8.0-zip \
    php8.0-gd \
    php8.0-intl \
    && sudo rm -rf /var/lib/apt/lists/*

RUN curl -sS https://getcomposer.org/installer | php \
    && mv composer.phar /usr/local/bin/composer

RUN echo 'export PATH="$PATH:$HOME/.composer/vendor/bin"' >> /root/.bashrc

RUN a2enmod rewrite

RUN chmod 777 /var/www/html

ENV EXTENSION_LIST="christian-kohler.path-intellisense,formulahendry.auto-close-tag,formulahendry.auto-rename-tag"

USER vscode

EXPOSE 80